### ISSUE TITLE
Bug with counting time Exoplayer 2.17.0 

### ISSUE THREAD

**Issue by Stinger2198** [amzn/exoplayer-amazon-port#117]
ExoPlayer version 2.17.0
Android version 7
Android device - Amazon Fire tv stick
When watching a video (streaming from the link), the video comes to the end of time but seconds continue to go further (for example, the video 30 seconds, when the video came to the end, the picture hangs, but the seconds continue to go 56/30) before updating the library, the OnPlayerStateChanged method from Playereventlistener class worked fine and now it is randomly, it can work immediately, and can after 30 seconds over time the video duration (59 out of 30 seconds) can work in a minute of 90 out of 30 seconds.
I can add apk for you test or example code from app.
My company using your player a long time and we never have had problem with that, but it came.
Thank you for help!
![158827506-5c08a2ff-b6ac-4805-a4ae-a2f4ab265842](https://user-images.githubusercontent.com/30195609/161279572-89900b3c-d17e-4470-9d2f-23d5cf5ff510.jpg)
!

**Comment by Stinger2198** [comment]
Video link - https://cdn.brid.tv/live/partners/7343/hd/443852.mp4
Playing finished 04:53/03:45
Using ExoPlayer version 2.17.0

**Comment by Stinger2198** [comment]
The player did not detect that the video has ended and continues to count

**Comment by saumya-y** [comment]
@Stinger2198, can you provide us with adb logs from your device for analysis, which fireOS version is your device running on?

**Comment by Stinger2198** [comment]
Hi @saumya-y 
Software version Fire OS 5.2.8.7 Fire TV Home Version
ADB log i can provide for you on monday, also i can give you apk for install on fire tv and test

**Comment by Stinger2198** [comment]
Hi @saumya-y 
This log when hanging video and counting time
[adb_log_fire_tv.txt](https://github.com/amzn/exoplayer-amazon-port/files/8410639/adb_log_fire_tv.txt)

**Comment by Stinger2198** [comment]
Somebody can check this log and explain - how that possible?
Video plays longer than its duration (see log)
[log_exoplayer.txt](https://github.com/amzn/exoplayer-amazon-port/files/8513093/log_exoplayer.txt)

**Comment by sbbanore** [comment]
@Stinger2198 - We tried testing the content URL provided by you on two of the FireTV sticks with FireOS version 5 but unfortunately the issue was not reproducible with it. Could you please provide the screenshot of the Settings page showing the device details? The exact device details will help us reproducing the issue on our end with the right device.

I went through the logcat logs attached with the issue - [adb_log_fire_tv.txt](https://github.com/amzn/exoplayer-amazon-port/files/8410639/adb_log_fire_tv.txt). The logcat logs do not provide much data as it only contains content progress and ad progress related lines repeatedly throughout the file. Can you please also help capturing the correct logs containing Exoplayer's Eventlogger data as well? Thanks.

**Comment by Stinger2198** [comment]
@sbbanore Thank you for paid attention to my question. I have found where was the problem. It was with my xml tags. Thank you a lot for answer. Now all working fine.
