### ISSUE TITLE
Native crash in Amazon Kindle Fire HD 7" (2013) when trying to play SmoothStreaming SuperSpeed content in  ExoPlayer demo app

### ISSUE THREAD

**Issue by moacir69** [amzn/exoplayer-amazon-port#16]
### Issue description
There is a native crash in Amazon Kindle Fire HD 7" (2013) when trying to play SmoothStreaming SuperSpeed content in  ExoPlayer demo app.
The same video plays well if Big Buck Bunny (MP4 Video) is played first.

### Reproduction steps
Install ExoPlayer demo app in an Amazon Kindle Fire HD 7" (2013) and attempt to perform the playback of SmoothStreaming SuperSpeed content.

### Link to test content
http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism

### Version of ExoPlayer being used
2.3.1

### Device(s) and version(s) of Android being used
Amazon Kindle Fire HD 7" (2013) / Fire OS 4.5.5.2 / (Init 2.3.1 [soho, KFSOWI, Amazon, 19])

### A full bug report captured from the device
Attached file 'bugReport.txt'

**Comment by moacir69** [comment]
[bugReport.txt](https://github.com/amzn/exoplayer-amazon-port/files/993198/bugReport.txt)

**Comment by peddisri** [comment]
The device you are testing on is a pretty old device and I don't think we have any plans to support any changes to is. So device side fix is ruled out. 

Exoplayer workaround:
Basically, Exoplayer is trying to set max input frame size to the AVC decoder more than what the decoder supports. 
A similar fix has been done for Fire TV Gen2. 
https://github.com/amzn/exoplayer-amazon-port/commit/ac78d9d360cb93c01cd14eb42677e969a766333a

Perhaps you can try to enable this for the device you are testing and find the max input size supported and limit it to that. 

Unfortunately, I don;t have device, and won't be able to find one soon. The best option here is if you can help to verify since you have the device.

**Comment by moacir69** [comment]
Thank you for your quick analysis.
I will try your suggestion in the device where the issue was happening.
Thank you.

**Comment by moacir69** [comment]
Using your suggestion as base seems to fix the issue.
Thanks!

**Comment by peddisri** [comment]
Thanks for your help. What was the buffer size limit that you set?

**Comment by moacir69** [comment]
You welcome.
It was set to 0.5 MB.
Thank you
