### ISSUE TITLE
Update README with details

### ISSUE THREAD

**Issue by brian-chu-twc** [amzn/exoplayer-amazon-port#3]
Can you explain:
- What version of the Exoplayer is this based on?
- Is that a divergent from Exoplayer or is that inclusive (i.e. I can use this build for my app not only in amazon device but also other devices).

**Comment by peddisri** [comment]
For each Exoplayer version rx.y.z, we maintain amazon/rx.y.z. Some versions (example 1.5.4) was not ported because within a week of its release 1.5.5 was released. So we decided to skip one version. If for some reason, you need a specific version that was not ported - please open an issue here.

 We have taken extra precaution to make sure all the device specific patches impact only the intended Amazon device. However, we do not test on other non-Amazon Android devices. 

So to answer you question, yes it is inclusive, i.e you can use it to build app on any Android device. 
However, if you find a bug on non-Amazon device and if it is reproduced in Googl'e exoplayer too, then the issue should be logged with Google. But if you find that one of amazon patches has caused this issue in Amazon's port of Exoplayer, please open a issue in this Github repo.

The intention of this repo is to make sure Google's Exoplayer works on Amazon devices.

**Comment by brian-chu-twc** [comment]
👍 😄
