### ISSUE TITLE
Publish to jCenter

### ISSUE THREAD

**Issue by brian-chu-twc** [amzn/exoplayer-amazon-port#4]
Will you be able to publish the binary to jCenter? or stay with using jar?
Thanks

**Comment by peddisri** [comment]
We have now published the jars to jcenter.

https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer-core
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer-hls
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer-ui
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer-smoothstreaming
https://bintray.com/exo-support-amzn/amazon-exoplayer-port/exoplayer-dash

**Comment by carloshwa** [comment]
Thanks for that. Note: Since the extension modules are not provided under `com.amazon.android`, if you want to use any of the ExoPlayer extensions with this, you'll need to set the `transitive` property to those dependencies to `false`. Otherwise, if you include one of the extensions from `com.google.android.exoplayer`, it will include dependencies for the core exoplayer libraries from `com.google.android.exoplayer` as well, clashing with the ones from `com.amazon.android`.

```
    compile "com.amazon.android:exoplayer:r2.4.4"
    compile ("com.google.android.exoplayer:extension-okhttp:r2.4.4") {
        transitive = false
    }
```

**Comment by peddisri** [comment]
Extensions will be made available by the end of the day.

**Comment by aitorgomez** [comment]
I know the issue is closed and that extensions were published to jcenter and aparently it's fine (https://bintray.com/exo-support-amzn/amazon-exoplayer-port/extension-ima/2.6.1) but I must be missing something because I'm getting the Failed to Resolve error on ima extension

Error:(258, 26) Failed to resolve: com.amazon.android:extension-ima:2.6.1

**Comment by peddisri** [comment]
Yeah this is strange. I'm facing this issue too. However, other extension like gvr works. I'll delete this and try to publish again

**Comment by peddisri** [comment]
I republished the jar. still it does not work

**Comment by aitorgomez** [comment]
True. I just added okhttp extension and it works, but ima doesn't
