### ISSUE TITLE
Failed to resolve: play-services-basement

### ISSUE THREAD

**Issue by abhishek-gangwar** [amzn/exoplayer-amazon-port#56]
Gradle project sync is failing with this error for the cast and ima extensions and even library-core.

including this library locally is causing this issue.

**Comment by peddisri** [comment]
Thanks for reporting. We'll look into this.

**Comment by peddisri** [comment]
This issue is seen in google's original code as well. 
https://repo.jfrog.org/artifactory/libs-release-bintray/com/google/android/ 
This does not have gms at all. The failure says 

Could not resolve all files for configuration ':demo:withExtensionsDebugRuntimeClasspath'.
> Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar

So looks like some issue with Google's bintray repo of gms modules. Please report this issue to google's repo.

**Comment by tmm1** [comment]
Workaround in https://github.com/google/ExoPlayer/issues/4997#issuecomment-432191486 was committed to upstream as https://github.com/google/ExoPlayer/commit/5ae60a6f18d564e7b174f4ec593f85f42eb97298
