### ISSUE TITLE
4K FTV Stick (AFTMM) renders green screen only for some mpeg2 videos

### ISSUE THREAD

**Issue by tmm1** [amzn/exoplayer-amazon-port#58]
### Issue description

Some interlaced mpeg2 videos will not render correctly. Most frames are missing and show a green screen, and occasionally one frame will render to the screen.

### Reproduction steps

Play https://s3.amazonaws.com/tmm1/us-ota-greenflash-aftmm.mpg inside Exoplayer on AFTMM device.

### Version of ExoPlayer being used

amazon/r2.8.4 (302d5574e21ca8039856b81f555a3ba3b6273ce8)

### Device(s) and version(s) of Android being used

AFTMM (N6232/1264)

**Comment by rinoshs** [comment]
We are able to reproduce the issue.  We are working on it.

**Comment by tmm1** [comment]
Thanks @rinoshs. Let me know if any other info is required.

**Comment by tmm1** [comment]
Hi, is there any update on this issue?

**Comment by rinoshs** [comment]
The issue has been root caused to vendor drivers.  We are following up with the vendor for a fix.

**Comment by drdrus** [comment]
not sure if the same issue causes this problem but there is a problem with hardware accelerated deinterlacing on the new Fire TV Stick 4K. Playing 1080i h264 in kodi is not possible. Turning off Hardware acceleration plays it but the video is laggy and unwatchable. I'm not sure if support for mpeg4 hardware accelerated deinterlacing was intended to be a feature ...

**Comment by tmm1** [comment]
@rinoshs was this fixed in NS6258/1604

**Comment by Nexus747** [comment]
My FireTV 4k plays a 1080i channel for a few mins after rebooting, but after that (or if I change channels), it locks up - black screen. I'm using the HDHomeRun app. Exiting and reopening the app doesn't help, it won't play at all then, just black screen. Could this be caused by the same bug?
Thanks!

**Comment by tmm1** [comment]
Any updates?

**Comment by rinoshs** [comment]
We are continuing to work with the vendor on a fix.

**Comment by tmm1** [comment]
@rinoshs for which issue? The green screen isn't happening anymore so it seems to be fixed in the last FireOS release. But the decoder still seems to crash after a few minutes on some streams and needs a reboot of the device to start decoding video again.

**Comment by puppinoo** [comment]
Same here. Device hangs after a few minutes while streaming from my enigma 2 decoder and crashes. Device needs to be rebooted.

**Comment by iandarbey** [comment]
The 1080i h264 remains. Evident on uk freesat HD channels (bbc, channel 4 etc) via tvheadend. Similar behaviour as described above, works for few mins, hangs, needs reboot.

Will this be fixed soon? The 4K stick’s one giant drawback for me (I’d be buying 3 more immediately if it’s sorted and getting rid of old mini pc’s).

**Comment by der-graph** [comment]
I can confirm that h264 1080i deinterlacing still doesn't work with this 4K Stick. So watching live tv in Europe (h264 1080i 50Hz) is not possible at the moment. Will this also be fixed soon?

**Comment by t0mmm** [comment]
Be great to get an update on the 1080i deinterlacing issue, it's severely limiting my use of the device at the moment.

**Comment by rinoshs** [comment]
The issue is fixed and will be pushed out in an upcoming system ota.

**Comment by iandarbey** [comment]
To clarify you’re referring to the h264 deinterlacing issue?

**Comment by der-graph** [comment]
... that's the big question here. If the answer is "yes", we are more than happy to look forward to the ota update. 
If rinosh is talking only about the mpeg2 deinterlacing issue we should probably open a new issue here on github. Nevertheless it would be nice to know if it is really a bug then and the device is capable of deinterlacing h264 content with accurate vendor drivers...

**Comment by just2mad** [comment]
> 
> 
> The issue is fixed and will be pushed out in an upcoming system ota.

when?

**Comment by humiboy** [comment]
When come new Fire TV Stick 4K Update for solved issues watching Live TV after a few changing channels all blocked black screen nothing more works. Only reboot works again for a few streams and then again blocked black screen...

I have bought 3 Fire TV 4K Sticks and all working bad and this is absolutly undiskutable.

All other FireTV devices have no problem only the Fire TV 4K Stick have big problem by watchin Live TV.

Please rollout new firmware for test. All firmware is better as the public firmware 6.2.5.8.

I would send all all FireTV 4K Sticks to retoure back but i have hope Amazon can fix this problem.

And i have green picture too. This problem is still not solved.

And why newest Fire TV 4K Sticks have no peoblem but only older Fire TV 4K Sticks have this big issue?

Give it a Hardware Isses Charge by the first production from FireTV 4K Stick ?

**Comment by rinoshs** [comment]
The fix is for the mpeg deinterlacing issue.  The fix is planned for OTA by the end of Q2.  Issue #81 is tracking the H264 deinterlacing issue.

**Comment by humiboy** [comment]
When the new Update rollout the problem with Live TV is fixed? No more black screen or crashes the apps? No more green screen?

**Comment by humiboy** [comment]
When come the big software update for fix many problems ?

**Comment by humiboy** [comment]
Why this fix is planned for OTA by the end of Q2???

Why so long still waiting????

**Comment by rinoshs** [comment]
System OTA schedules are planned in advance and have a high bar.  Fixes need to go through a bake time before release.

**Comment by weakfl** [comment]
With firmware update 6.2.6.3 deinterlacing of SD content isn't working anymore either. So way to go ;)

**Comment by rinoshs** [comment]
@weakfl,

Could you confirm that you are seeing the issue with Mpeg SD interlaced content? Was this content working on build numbers previous to 6.2.6.3?

**Comment by weakfl** [comment]
@rinoshs

> Could you confirm that you are seeing the issue with Mpeg SD interlaced content?

mpeg2, 720x576@50i (german satelite tv)

> Was this content working on build numbers previous to 6.2.6.3?

Yes, it was.

**Comment by peterthorpe81** [comment]
@weakfl I had deinterlace issues on Mpeg 2 SD content before the update (Source UK Freesat mpeg2 50i). The stream would appear to work for a few minutes to as long as an hour and then crash out. Are you sure it wasn't an issue before and you just hadn't noticed because it takes much longer to fail?

For those using TVHeadend or similar as a source I suggest you look if there is a transcoding workaround for you. I have setup TVHeadend transcoding to x264 progressive on my cheap Intel J1900 system which is working reliably.

**Comment by weakfl** [comment]
@peterthorpe81

> I had deinterlace issues on Mpeg 2 SD content before the update (Source UK Freesat mpeg2 50i). The stream would appear to work for a few minutes to as long as an hour and then crash out. Are you sure it wasn't an issue before and you just hadn't noticed because it takes much longer to fail?

I did have intermittent issues where mpeg2 content would crash and require a restart of the aftv stick, but it was working ok most of the time.
And most importantly, the SD content was deinterlaced properly. With fw 6.2.6.3 mpeg2 SD content is still playing, but is not deinterlaced anymore.  I noticed the combing artifacts immediately.

I probably should have been more precise when mentioning the issue.

**Comment by humiboy** [comment]
Any news to fix this problem?

**Comment by humiboy** [comment]
When come the big software update what fix this problems?

**Comment by weakfl** [comment]
> When come the big software update what fix this problems?

I wouldn't hold my breath…

**Comment by rinoshs** [comment]
This fix is planned for end of Q2.  The update should start going out to devices by the end of June.

**Comment by Mottarello** [comment]
Hi, we are end of Q2 but same behaviour with the OS 6.2.6.4 latest version installed today on a fire TV.

**Comment by Arcitec** [comment]
I am on the new OS released 2 days ago:

```
Fire OS 6.2.6.4 (NS6264/1995)
Fire TV Home Version 6.1.6.0-727
```

I played the mpg file in the first post. In MX player and Kodi. Both using hardware decoding and deinterlacing. In MX I used both HW+ and HW hardware modes.

Mx: green flash at start for 0.5 seconds (lack of keyframe) and then the screen fixes itself (keyframe) and plays perfectly with no green flashes for the duration of the entire video

Kodi: skips the green flash (lack of keyframe) and immediately begins playback with a perfect picture. And stays perfect. If I rewind to the start in Kodi I still miss some of the initial words of audio which PROVES that Kodi intentionally skips until the first keyframe.

Those who don’t know what i mean by keyframe: Go to google and educate yourselves.

So anyway; yes the latest update fixes the issue. I can play the video and never get any green flashing. The only flash I got was completely natural and expected - in MX player which plays the video from the exact start despite lacking a keyframe there which means the screen starts out green (empty decoder buffer), is then partially filled with some blocks of data. And then replaced by a full, perfect keyframe half a second later.

Conclusion: The video file IS corrupt at the start (has no keyframe). The FireTV with latest update handles that PERFECTLY, exactly as it should. First a small green flash (if the player starts the corrupt video at the absolute start before any keyframe). And no green flashes happen during playback AFTER a keyframe has been received. FireTV 4k hardware decoding of this file is behaving EXACTLY as it should. This issue is solved!

**Comment by macamba** [comment]
Hi all,
This issue is not solved yet
I'm having problems with video TV stream from my provider internet Movistar (Spain) to playing h264 format under m2ts/ts.
I get video freeze at few seconds to start video playing.
I was talking with support from Kodi to analyst my debug logs and they have identified issue "Interlaced H264 - not (fully) supported by FireTV 4K". Also others apps give problems
I could provide you pieces of video to diferentes format (SD, HD, UHD) under m2ts/ts in h264 from my streaming IPTV TV to check this issue and reach the root of cause

Thanks

**Comment by macamba** [comment]
Several discussions about this issue not solved yet for too many users

https://forum.kodi.tv/showthread.php?tid=337702&page=4

https://forum.silicondust.com/forum/viewtopic.php?f=119&t=70081&sid=1508ae8e6f6861823aaf44f88131f1fd&start=180

**Comment by tonywagner** [comment]
> Hi all,
> This issue is not solved yet
> I'm having problems with video TV stream from my provider internet Movistar (Spain) to playing h264 format under m2ts/ts.

FYI, this issue was about MPEG2 video, not H264.

You might want to follow this other issue instead:
https://github.com/amzn/exoplayer-amazon-port/issues/94
